%YAML 1.2
---
# Default parameters for the Tracking program
# All parameters can be changed to accommodate user needs.
# All parameters can be changed at runtime with the appropriate config window
User:
  name: Aquiles

saving:
  auto_save: False
  auto_save_waterfall: True
  directory: /home/aquiles/
  filename_video: Video # Can be the same filename for video and photo
  filename_photo: Snap
  filename_waterfall: Waterfall
  filename_trajectory: Trajectory
  filename_log: Log
  max_memory: 800 # In megabytes

GUI:
  length_waterfall: 20 # Total length of the Waterfall (lines)
  refresh_time: 100 # Refresh rate of the GUI (in ms)

camera:
  model: dummy_camera # Should be a python file in model/cameras
  init: 0 # Initial arguments to pass when creating the camera
  #extra_args: [extra, arguments] # Extra arguments that can be passed when constructing the model
  model_camera: Orca Flash # To keep a registry of which camera was used in the experiment
  exposure_time: 200ms # Initial exposure time (in ms)
  binning_x: 1 # Binning
  binning_y: 1
  roi_x1: 0
  roi_x2: 200
  roi_y1: 0
  roi_y2: 200
  background: '' # Full path to background file, or empty for none.
  background_method: [Method1, Method2]

waterfall: # Parameters for calculating the waterfall plot
  length: 20  # The total length of the waterfall (lines)
  vertical_bin: 10  # Total number of lines of the CCD to integrate

movie:
  buffer_length: 1000 # Frames

Tracking: # Not yet implemented, will show up in the config window
  param_1: 0.
  param_2: 0

Debug:
  queue_memory: False
  to_screen: True
